#define make_clean_mc_B2Dpppi_cxx
#include "make_clean_mc_B2Dpppi.h"
#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>
#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TCanvas.h"
#include "TChain.h"
#include "TLorentzVector.h"
#include "TSystem.h"
#include "fstream"
#include "iostream"
#include <iomanip>
#include <math.h>
#include "TRandom3.h"

void make(TString Input, TString Output, TString branch)
{
                //do for data
                TChain *dis_chain = new TChain(branch, branch);
                dis_chain->Add(Input);
                cout<<"====Loaded the files. Please be patient......======"<<endl;
                cout<<"Loding   --- "   << Input  << endl;
                cout<<"TreeName --- "   << branch << endl;
                cout<<"Total entries : "<< dis_chain->GetEntries()<<endl;
                cout<<"Output   --- "   << Output << endl;

                dis_chain -> SetBranchStatus("*Fit_*",0);
        

                dis_chain -> SetBranchStatus("B*_nPV",1);

                TFile *newf = new TFile(Output,"recreate");
                TTree* t_data = dis_chain->CloneTree(0);

                dis_chain -> SetBranchStatus("*Fit_*",1);

                Double_t B0_PVALLFit_Dplus_Kplus_ID;                            t_data->Branch("B0_PVALLFit_Dplus_Kplus_ID", &B0_PVALLFit_Dplus_Kplus_ID, "B0_PVALLFit_Dplus_Kplus_ID/D");
                Double_t B0_PVALLFit_Dplus_Kplus_PE;                            t_data->Branch("B0_PVALLFit_Dplus_Kplus_PE", &B0_PVALLFit_Dplus_Kplus_PE, "B0_PVALLFit_Dplus_Kplus_PE/D");
                Double_t B0_PVALLFit_Dplus_Kplus_PX;                            t_data->Branch("B0_PVALLFit_Dplus_Kplus_PX", &B0_PVALLFit_Dplus_Kplus_PX, "B0_PVALLFit_Dplus_Kplus_PX/D");
                Double_t B0_PVALLFit_Dplus_Kplus_PY;                            t_data->Branch("B0_PVALLFit_Dplus_Kplus_PY", &B0_PVALLFit_Dplus_Kplus_PY, "B0_PVALLFit_Dplus_Kplus_PY/D");
                Double_t B0_PVALLFit_Dplus_Kplus_PZ;                            t_data->Branch("B0_PVALLFit_Dplus_Kplus_PZ", &B0_PVALLFit_Dplus_Kplus_PZ, "B0_PVALLFit_Dplus_Kplus_PZ/D");
                Double_t B0_PVALLFit_Dplus_M;                                   t_data->Branch("B0_PVALLFit_Dplus_M", &B0_PVALLFit_Dplus_M, "B0_PVALLFit_Dplus_M/D");
                Double_t B0_PVALLFit_Dplus_MERR;                                t_data->Branch("B0_PVALLFit_Dplus_MERR", &B0_PVALLFit_Dplus_MERR, "B0_PVALLFit_Dplus_MERR/D");
                Double_t B0_PVALLFit_Dplus_P;                                   t_data->Branch("B0_PVALLFit_Dplus_P", &B0_PVALLFit_Dplus_P, "B0_PVALLFit_Dplus_P/D");
                Double_t B0_PVALLFit_Dplus_PERR;                                t_data->Branch("B0_PVALLFit_Dplus_PERR", &B0_PVALLFit_Dplus_PERR, "B0_PVALLFit_Dplus_PERR/D");
                Double_t B0_PVALLFit_Dplus_ctau;                                t_data->Branch("B0_PVALLFit_Dplus_ctau", &B0_PVALLFit_Dplus_ctau, "B0_PVALLFit_Dplus_ctau/D");
                Double_t B0_PVALLFit_Dplus_ctauErr;                             t_data->Branch("B0_PVALLFit_Dplus_ctauErr", &B0_PVALLFit_Dplus_ctauErr, "B0_PVALLFit_Dplus_ctauErr/D");
                Double_t B0_PVALLFit_Dplus_decayLength;                         t_data->Branch("B0_PVALLFit_Dplus_decayLength", &B0_PVALLFit_Dplus_decayLength, "B0_PVALLFit_Dplus_decayLength/D");
                Double_t B0_PVALLFit_Dplus_decayLengthErr;                      t_data->Branch("B0_PVALLFit_Dplus_decayLengthErr", &B0_PVALLFit_Dplus_decayLengthErr, "B0_PVALLFit_Dplus_decayLengthErr/D");
                Double_t B0_PVALLFit_Dplus_piplus_0_ID;                         t_data->Branch("B0_PVALLFit_Dplus_piplus_0_ID", &B0_PVALLFit_Dplus_piplus_0_ID, "B0_PVALLFit_Dplus_piplus_0_ID/D");
                Double_t B0_PVALLFit_Dplus_piplus_0_PE;                         t_data->Branch("B0_PVALLFit_Dplus_piplus_0_PE", &B0_PVALLFit_Dplus_piplus_0_PE, "B0_PVALLFit_Dplus_piplus_0_PE/D");
                Double_t B0_PVALLFit_Dplus_piplus_0_PX;                         t_data->Branch("B0_PVALLFit_Dplus_piplus_0_PX", &B0_PVALLFit_Dplus_piplus_0_PX, "B0_PVALLFit_Dplus_piplus_0_PX/D");
                Double_t B0_PVALLFit_Dplus_piplus_0_PY;                         t_data->Branch("B0_PVALLFit_Dplus_piplus_0_PY", &B0_PVALLFit_Dplus_piplus_0_PY, "B0_PVALLFit_Dplus_piplus_0_PY/D");
                Double_t B0_PVALLFit_Dplus_piplus_0_PZ;                         t_data->Branch("B0_PVALLFit_Dplus_piplus_0_PZ", &B0_PVALLFit_Dplus_piplus_0_PZ, "B0_PVALLFit_Dplus_piplus_0_PZ/D");
                Double_t B0_PVALLFit_Dplus_piplus_ID;                           t_data->Branch("B0_PVALLFit_Dplus_piplus_ID", &B0_PVALLFit_Dplus_piplus_ID, "B0_PVALLFit_Dplus_piplus_ID/D");
                Double_t B0_PVALLFit_Dplus_piplus_PE;                           t_data->Branch("B0_PVALLFit_Dplus_piplus_PE", &B0_PVALLFit_Dplus_piplus_PE, "B0_PVALLFit_Dplus_piplus_PE/D");
                Double_t B0_PVALLFit_Dplus_piplus_PX;                           t_data->Branch("B0_PVALLFit_Dplus_piplus_PX", &B0_PVALLFit_Dplus_piplus_PX, "B0_PVALLFit_Dplus_piplus_PX/D");
                Double_t B0_PVALLFit_Dplus_piplus_PY;                           t_data->Branch("B0_PVALLFit_Dplus_piplus_PY", &B0_PVALLFit_Dplus_piplus_PY, "B0_PVALLFit_Dplus_piplus_PY/D");
                Double_t B0_PVALLFit_Dplus_piplus_PZ;                           t_data->Branch("B0_PVALLFit_Dplus_piplus_PZ", &B0_PVALLFit_Dplus_piplus_PZ, "B0_PVALLFit_Dplus_piplus_PZ/D");
                Double_t B0_PVALLFit_M;                                         t_data->Branch("B0_PVALLFit_M", &B0_PVALLFit_M, "B0_PVALLFit_M/D");
                Double_t B0_PVALLFit_MERR;                                      t_data->Branch("B0_PVALLFit_MERR", &B0_PVALLFit_MERR, "B0_PVALLFit_MERR/D");
                Double_t B0_PVALLFit_P;                                         t_data->Branch("B0_PVALLFit_P", &B0_PVALLFit_P, "B0_PVALLFit_P/D");
                Double_t B0_PVALLFit_PERR;                                      t_data->Branch("B0_PVALLFit_PERR", &B0_PVALLFit_PERR, "B0_PVALLFit_PERR/D");
                Double_t B0_PVALLFit_PV_X;                                      t_data->Branch("B0_PVALLFit_PV_X", &B0_PVALLFit_PV_X, "B0_PVALLFit_PV_X/D");
                Double_t B0_PVALLFit_PV_Y;                                      t_data->Branch("B0_PVALLFit_PV_Y", &B0_PVALLFit_PV_Y, "B0_PVALLFit_PV_Y/D");
                Double_t B0_PVALLFit_PV_Z;                                      t_data->Branch("B0_PVALLFit_PV_Z", &B0_PVALLFit_PV_Z, "B0_PVALLFit_PV_Z/D");
                Double_t B0_PVALLFit_PV_key;                                    t_data->Branch("B0_PVALLFit_PV_key", &B0_PVALLFit_PV_key, "B0_PVALLFit_PV_key/D");
                Double_t B0_PVALLFit_a_1_1260_plus_M;                           t_data->Branch("B0_PVALLFit_a_1_1260_plus_M", &B0_PVALLFit_a_1_1260_plus_M, "B0_PVALLFit_a_1_1260_plus_M/D");
                Double_t B0_PVALLFit_a_1_1260_plus_MERR;                        t_data->Branch("B0_PVALLFit_a_1_1260_plus_MERR", &B0_PVALLFit_a_1_1260_plus_MERR, "B0_PVALLFit_a_1_1260_plus_MERR/D");
                Double_t B0_PVALLFit_a_1_1260_plus_P;                           t_data->Branch("B0_PVALLFit_a_1_1260_plus_P", &B0_PVALLFit_a_1_1260_plus_P, "B0_PVALLFit_a_1_1260_plus_P/D");
                Double_t B0_PVALLFit_a_1_1260_plus_PERR;                        t_data->Branch("B0_PVALLFit_a_1_1260_plus_PERR", &B0_PVALLFit_a_1_1260_plus_PERR, "B0_PVALLFit_a_1_1260_plus_PERR/D");
                Double_t B0_PVALLFit_a_1_1260_plus_ctau;                        t_data->Branch("B0_PVALLFit_a_1_1260_plus_ctau", &B0_PVALLFit_a_1_1260_plus_ctau, "B0_PVALLFit_a_1_1260_plus_ctau/D");
                Double_t B0_PVALLFit_a_1_1260_plus_ctauErr;                     t_data->Branch("B0_PVALLFit_a_1_1260_plus_ctauErr", &B0_PVALLFit_a_1_1260_plus_ctauErr, "B0_PVALLFit_a_1_1260_plus_ctauErr/D");
                Double_t B0_PVALLFit_a_1_1260_plus_decayLength;                 t_data->Branch("B0_PVALLFit_a_1_1260_plus_decayLength", &B0_PVALLFit_a_1_1260_plus_decayLength, "B0_PVALLFit_a_1_1260_plus_decayLength/D");
                Double_t B0_PVALLFit_a_1_1260_plus_decayLengthErr;              t_data->Branch("B0_PVALLFit_a_1_1260_plus_decayLengthErr", &B0_PVALLFit_a_1_1260_plus_decayLengthErr, "B0_PVALLFit_a_1_1260_plus_decayLengthErr/D");
                Double_t B0_PVALLFit_a_1_1260_plus_piplus_ID;                   t_data->Branch("B0_PVALLFit_a_1_1260_plus_piplus_ID", &B0_PVALLFit_a_1_1260_plus_piplus_ID, "B0_PVALLFit_a_1_1260_plus_piplus_ID/D");
                Double_t B0_PVALLFit_a_1_1260_plus_piplus_PE;                   t_data->Branch("B0_PVALLFit_a_1_1260_plus_piplus_PE", &B0_PVALLFit_a_1_1260_plus_piplus_PE, "B0_PVALLFit_a_1_1260_plus_piplus_PE/D");
                Double_t B0_PVALLFit_a_1_1260_plus_piplus_PX;                   t_data->Branch("B0_PVALLFit_a_1_1260_plus_piplus_PX", &B0_PVALLFit_a_1_1260_plus_piplus_PX, "B0_PVALLFit_a_1_1260_plus_piplus_PX/D");
                Double_t B0_PVALLFit_a_1_1260_plus_piplus_PY;                   t_data->Branch("B0_PVALLFit_a_1_1260_plus_piplus_PY", &B0_PVALLFit_a_1_1260_plus_piplus_PY, "B0_PVALLFit_a_1_1260_plus_piplus_PY/D");
                Double_t B0_PVALLFit_a_1_1260_plus_piplus_PZ;                   t_data->Branch("B0_PVALLFit_a_1_1260_plus_piplus_PZ", &B0_PVALLFit_a_1_1260_plus_piplus_PZ, "B0_PVALLFit_a_1_1260_plus_piplus_PZ/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_0_ID;                  t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_0_ID", &B0_PVALLFit_a_1_1260_plus_pplus_0_ID, "B0_PVALLFit_a_1_1260_plus_pplus_0_ID/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_0_PE;                  t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_0_PE", &B0_PVALLFit_a_1_1260_plus_pplus_0_PE, "B0_PVALLFit_a_1_1260_plus_pplus_0_PE/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_0_PX;                  t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_0_PX", &B0_PVALLFit_a_1_1260_plus_pplus_0_PX, "B0_PVALLFit_a_1_1260_plus_pplus_0_PX/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_0_PY;                  t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_0_PY", &B0_PVALLFit_a_1_1260_plus_pplus_0_PY, "B0_PVALLFit_a_1_1260_plus_pplus_0_PY/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_0_PZ;                  t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_0_PZ", &B0_PVALLFit_a_1_1260_plus_pplus_0_PZ, "B0_PVALLFit_a_1_1260_plus_pplus_0_PZ/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_ID;                    t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_ID", &B0_PVALLFit_a_1_1260_plus_pplus_ID, "B0_PVALLFit_a_1_1260_plus_pplus_ID/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_PE;                    t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_PE", &B0_PVALLFit_a_1_1260_plus_pplus_PE, "B0_PVALLFit_a_1_1260_plus_pplus_PE/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_PX;                    t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_PX", &B0_PVALLFit_a_1_1260_plus_pplus_PX, "B0_PVALLFit_a_1_1260_plus_pplus_PX/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_PY;                    t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_PY", &B0_PVALLFit_a_1_1260_plus_pplus_PY, "B0_PVALLFit_a_1_1260_plus_pplus_PY/D");
                Double_t B0_PVALLFit_a_1_1260_plus_pplus_PZ;                    t_data->Branch("B0_PVALLFit_a_1_1260_plus_pplus_PZ", &B0_PVALLFit_a_1_1260_plus_pplus_PZ, "B0_PVALLFit_a_1_1260_plus_pplus_PZ/D");
                Double_t B0_PVALLFit_chi2;                                      t_data->Branch("B0_PVALLFit_chi2", &B0_PVALLFit_chi2, "B0_PVALLFit_chi2/D");
                Double_t B0_PVALLFit_ctau;                                      t_data->Branch("B0_PVALLFit_ctau", &B0_PVALLFit_ctau, "B0_PVALLFit_ctau/D");
                Double_t B0_PVALLFit_ctauErr;                                   t_data->Branch("B0_PVALLFit_ctauErr", &B0_PVALLFit_ctauErr, "B0_PVALLFit_ctauErr/D");
                Double_t B0_PVALLFit_decayLength;                               t_data->Branch("B0_PVALLFit_decayLength", &B0_PVALLFit_decayLength, "B0_PVALLFit_decayLength/D");
                Double_t B0_PVALLFit_decayLengthErr;                            t_data->Branch("B0_PVALLFit_decayLengthErr", &B0_PVALLFit_decayLengthErr, "B0_PVALLFit_decayLengthErr/D");
                Double_t B0_PVALLFit_nDOF;                                      t_data->Branch("B0_PVALLFit_nDOF", &B0_PVALLFit_nDOF, "B0_PVALLFit_nDOF/D");
                Double_t B0_PVALLFit_nIter;                                     t_data->Branch("B0_PVALLFit_nIter", &B0_PVALLFit_nIter, "B0_PVALLFit_nIter/D");
                Double_t B0_PVALLFit_status;                                    t_data->Branch("B0_PVALLFit_status", &B0_PVALLFit_status, "B0_PVALLFit_status/D");
                Double_t B0_PVDFit_Dplus_Kplus_ID;                              t_data->Branch("B0_PVDFit_Dplus_Kplus_ID", &B0_PVDFit_Dplus_Kplus_ID, "B0_PVDFit_Dplus_Kplus_ID/D");
                Double_t B0_PVDFit_Dplus_Kplus_PE;                              t_data->Branch("B0_PVDFit_Dplus_Kplus_PE", &B0_PVDFit_Dplus_Kplus_PE, "B0_PVDFit_Dplus_Kplus_PE/D");
                Double_t B0_PVDFit_Dplus_Kplus_PX;                              t_data->Branch("B0_PVDFit_Dplus_Kplus_PX", &B0_PVDFit_Dplus_Kplus_PX, "B0_PVDFit_Dplus_Kplus_PX/D");
                Double_t B0_PVDFit_Dplus_Kplus_PY;                              t_data->Branch("B0_PVDFit_Dplus_Kplus_PY", &B0_PVDFit_Dplus_Kplus_PY, "B0_PVDFit_Dplus_Kplus_PY/D");
                Double_t B0_PVDFit_Dplus_Kplus_PZ;                              t_data->Branch("B0_PVDFit_Dplus_Kplus_PZ", &B0_PVDFit_Dplus_Kplus_PZ, "B0_PVDFit_Dplus_Kplus_PZ/D");
                Double_t B0_PVDFit_Dplus_M;                                     t_data->Branch("B0_PVDFit_Dplus_M", &B0_PVDFit_Dplus_M, "B0_PVDFit_Dplus_M/D");
                Double_t B0_PVDFit_Dplus_MERR;                                  t_data->Branch("B0_PVDFit_Dplus_MERR", &B0_PVDFit_Dplus_MERR, "B0_PVDFit_Dplus_MERR/D");
                Double_t B0_PVDFit_Dplus_P;                                     t_data->Branch("B0_PVDFit_Dplus_P", &B0_PVDFit_Dplus_P, "B0_PVDFit_Dplus_P/D");
                Double_t B0_PVDFit_Dplus_PERR;                                  t_data->Branch("B0_PVDFit_Dplus_PERR", &B0_PVDFit_Dplus_PERR, "B0_PVDFit_Dplus_PERR/D");
                Double_t B0_PVDFit_Dplus_ctau;                                  t_data->Branch("B0_PVDFit_Dplus_ctau", &B0_PVDFit_Dplus_ctau, "B0_PVDFit_Dplus_ctau/D");
                Double_t B0_PVDFit_Dplus_ctauErr;                               t_data->Branch("B0_PVDFit_Dplus_ctauErr", &B0_PVDFit_Dplus_ctauErr, "B0_PVDFit_Dplus_ctauErr/D");
                Double_t B0_PVDFit_Dplus_decayLength;                           t_data->Branch("B0_PVDFit_Dplus_decayLength", &B0_PVDFit_Dplus_decayLength, "B0_PVDFit_Dplus_decayLength/D");
                Double_t B0_PVDFit_Dplus_decayLengthErr;                        t_data->Branch("B0_PVDFit_Dplus_decayLengthErr", &B0_PVDFit_Dplus_decayLengthErr, "B0_PVDFit_Dplus_decayLengthErr/D");
                Double_t B0_PVDFit_Dplus_piplus_0_ID;                           t_data->Branch("B0_PVDFit_Dplus_piplus_0_ID", &B0_PVDFit_Dplus_piplus_0_ID, "B0_PVDFit_Dplus_piplus_0_ID/D");
                Double_t B0_PVDFit_Dplus_piplus_0_PE;                           t_data->Branch("B0_PVDFit_Dplus_piplus_0_PE", &B0_PVDFit_Dplus_piplus_0_PE, "B0_PVDFit_Dplus_piplus_0_PE/D");
                Double_t B0_PVDFit_Dplus_piplus_0_PX;                           t_data->Branch("B0_PVDFit_Dplus_piplus_0_PX", &B0_PVDFit_Dplus_piplus_0_PX, "B0_PVDFit_Dplus_piplus_0_PX/D");
                Double_t B0_PVDFit_Dplus_piplus_0_PY;                           t_data->Branch("B0_PVDFit_Dplus_piplus_0_PY", &B0_PVDFit_Dplus_piplus_0_PY, "B0_PVDFit_Dplus_piplus_0_PY/D");
                Double_t B0_PVDFit_Dplus_piplus_0_PZ;                           t_data->Branch("B0_PVDFit_Dplus_piplus_0_PZ", &B0_PVDFit_Dplus_piplus_0_PZ, "B0_PVDFit_Dplus_piplus_0_PZ/D");
                Double_t B0_PVDFit_Dplus_piplus_ID;                             t_data->Branch("B0_PVDFit_Dplus_piplus_ID", &B0_PVDFit_Dplus_piplus_ID, "B0_PVDFit_Dplus_piplus_ID/D");
                Double_t B0_PVDFit_Dplus_piplus_PE;                             t_data->Branch("B0_PVDFit_Dplus_piplus_PE", &B0_PVDFit_Dplus_piplus_PE, "B0_PVDFit_Dplus_piplus_PE/D");
                Double_t B0_PVDFit_Dplus_piplus_PX;                             t_data->Branch("B0_PVDFit_Dplus_piplus_PX", &B0_PVDFit_Dplus_piplus_PX, "B0_PVDFit_Dplus_piplus_PX/D");
                Double_t B0_PVDFit_Dplus_piplus_PY;                             t_data->Branch("B0_PVDFit_Dplus_piplus_PY", &B0_PVDFit_Dplus_piplus_PY, "B0_PVDFit_Dplus_piplus_PY/D");
                Double_t B0_PVDFit_Dplus_piplus_PZ;                             t_data->Branch("B0_PVDFit_Dplus_piplus_PZ", &B0_PVDFit_Dplus_piplus_PZ, "B0_PVDFit_Dplus_piplus_PZ/D");
                Double_t B0_PVDFit_M;                                           t_data->Branch("B0_PVDFit_M", &B0_PVDFit_M, "B0_PVDFit_M/D");
                Double_t B0_PVDFit_MERR;                                        t_data->Branch("B0_PVDFit_MERR", &B0_PVDFit_MERR, "B0_PVDFit_MERR/D");
                Double_t B0_PVDFit_P;                                           t_data->Branch("B0_PVDFit_P", &B0_PVDFit_P, "B0_PVDFit_P/D");
                Double_t B0_PVDFit_PERR;                                        t_data->Branch("B0_PVDFit_PERR", &B0_PVDFit_PERR, "B0_PVDFit_PERR/D");
                Double_t B0_PVDFit_PV_X;                                        t_data->Branch("B0_PVDFit_PV_X", &B0_PVDFit_PV_X, "B0_PVDFit_PV_X/D");
                Double_t B0_PVDFit_PV_Y;                                        t_data->Branch("B0_PVDFit_PV_Y", &B0_PVDFit_PV_Y, "B0_PVDFit_PV_Y/D");
                Double_t B0_PVDFit_PV_Z;                                        t_data->Branch("B0_PVDFit_PV_Z", &B0_PVDFit_PV_Z, "B0_PVDFit_PV_Z/D");
                Double_t B0_PVDFit_PV_key;                                      t_data->Branch("B0_PVDFit_PV_key", &B0_PVDFit_PV_key, "B0_PVDFit_PV_key/D");
                Double_t B0_PVDFit_a_1_1260_plus_M;                             t_data->Branch("B0_PVDFit_a_1_1260_plus_M", &B0_PVDFit_a_1_1260_plus_M, "B0_PVDFit_a_1_1260_plus_M/D");
                Double_t B0_PVDFit_a_1_1260_plus_MERR;                          t_data->Branch("B0_PVDFit_a_1_1260_plus_MERR", &B0_PVDFit_a_1_1260_plus_MERR, "B0_PVDFit_a_1_1260_plus_MERR/D");
                Double_t B0_PVDFit_a_1_1260_plus_P;                             t_data->Branch("B0_PVDFit_a_1_1260_plus_P", &B0_PVDFit_a_1_1260_plus_P, "B0_PVDFit_a_1_1260_plus_P/D");
                Double_t B0_PVDFit_a_1_1260_plus_PERR;                          t_data->Branch("B0_PVDFit_a_1_1260_plus_PERR", &B0_PVDFit_a_1_1260_plus_PERR, "B0_PVDFit_a_1_1260_plus_PERR/D");
                Double_t B0_PVDFit_a_1_1260_plus_ctau;                          t_data->Branch("B0_PVDFit_a_1_1260_plus_ctau", &B0_PVDFit_a_1_1260_plus_ctau, "B0_PVDFit_a_1_1260_plus_ctau/D");
                Double_t B0_PVDFit_a_1_1260_plus_ctauErr;                       t_data->Branch("B0_PVDFit_a_1_1260_plus_ctauErr", &B0_PVDFit_a_1_1260_plus_ctauErr, "B0_PVDFit_a_1_1260_plus_ctauErr/D");
                Double_t B0_PVDFit_a_1_1260_plus_decayLength;                   t_data->Branch("B0_PVDFit_a_1_1260_plus_decayLength", &B0_PVDFit_a_1_1260_plus_decayLength, "B0_PVDFit_a_1_1260_plus_decayLength/D");
                Double_t B0_PVDFit_a_1_1260_plus_decayLengthErr;                t_data->Branch("B0_PVDFit_a_1_1260_plus_decayLengthErr", &B0_PVDFit_a_1_1260_plus_decayLengthErr, "B0_PVDFit_a_1_1260_plus_decayLengthErr/D");
                Double_t B0_PVDFit_a_1_1260_plus_piplus_ID;                     t_data->Branch("B0_PVDFit_a_1_1260_plus_piplus_ID", &B0_PVDFit_a_1_1260_plus_piplus_ID, "B0_PVDFit_a_1_1260_plus_piplus_ID/D");
                Double_t B0_PVDFit_a_1_1260_plus_piplus_PE;                     t_data->Branch("B0_PVDFit_a_1_1260_plus_piplus_PE", &B0_PVDFit_a_1_1260_plus_piplus_PE, "B0_PVDFit_a_1_1260_plus_piplus_PE/D");
                Double_t B0_PVDFit_a_1_1260_plus_piplus_PX;                     t_data->Branch("B0_PVDFit_a_1_1260_plus_piplus_PX", &B0_PVDFit_a_1_1260_plus_piplus_PX, "B0_PVDFit_a_1_1260_plus_piplus_PX/D");
                Double_t B0_PVDFit_a_1_1260_plus_piplus_PY;                     t_data->Branch("B0_PVDFit_a_1_1260_plus_piplus_PY", &B0_PVDFit_a_1_1260_plus_piplus_PY, "B0_PVDFit_a_1_1260_plus_piplus_PY/D");
                Double_t B0_PVDFit_a_1_1260_plus_piplus_PZ;                     t_data->Branch("B0_PVDFit_a_1_1260_plus_piplus_PZ", &B0_PVDFit_a_1_1260_plus_piplus_PZ, "B0_PVDFit_a_1_1260_plus_piplus_PZ/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_0_ID;                    t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_0_ID", &B0_PVDFit_a_1_1260_plus_pplus_0_ID, "B0_PVDFit_a_1_1260_plus_pplus_0_ID/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_0_PE;                    t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_0_PE", &B0_PVDFit_a_1_1260_plus_pplus_0_PE, "B0_PVDFit_a_1_1260_plus_pplus_0_PE/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_0_PX;                    t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_0_PX", &B0_PVDFit_a_1_1260_plus_pplus_0_PX, "B0_PVDFit_a_1_1260_plus_pplus_0_PX/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_0_PY;                    t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_0_PY", &B0_PVDFit_a_1_1260_plus_pplus_0_PY, "B0_PVDFit_a_1_1260_plus_pplus_0_PY/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_0_PZ;                    t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_0_PZ", &B0_PVDFit_a_1_1260_plus_pplus_0_PZ, "B0_PVDFit_a_1_1260_plus_pplus_0_PZ/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_ID;                      t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_ID", &B0_PVDFit_a_1_1260_plus_pplus_ID, "B0_PVDFit_a_1_1260_plus_pplus_ID/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_PE;                      t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_PE", &B0_PVDFit_a_1_1260_plus_pplus_PE, "B0_PVDFit_a_1_1260_plus_pplus_PE/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_PX;                      t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_PX", &B0_PVDFit_a_1_1260_plus_pplus_PX, "B0_PVDFit_a_1_1260_plus_pplus_PX/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_PY;                      t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_PY", &B0_PVDFit_a_1_1260_plus_pplus_PY, "B0_PVDFit_a_1_1260_plus_pplus_PY/D");
                Double_t B0_PVDFit_a_1_1260_plus_pplus_PZ;                      t_data->Branch("B0_PVDFit_a_1_1260_plus_pplus_PZ", &B0_PVDFit_a_1_1260_plus_pplus_PZ, "B0_PVDFit_a_1_1260_plus_pplus_PZ/D");
                Double_t B0_PVDFit_chi2;                                        t_data->Branch("B0_PVDFit_chi2", &B0_PVDFit_chi2, "B0_PVDFit_chi2/D");
                Double_t B0_PVDFit_ctau;                                        t_data->Branch("B0_PVDFit_ctau", &B0_PVDFit_ctau, "B0_PVDFit_ctau/D");
                Double_t B0_PVDFit_ctauErr;                                     t_data->Branch("B0_PVDFit_ctauErr", &B0_PVDFit_ctauErr, "B0_PVDFit_ctauErr/D");
                Double_t B0_PVDFit_decayLength;                                 t_data->Branch("B0_PVDFit_decayLength", &B0_PVDFit_decayLength, "B0_PVDFit_decayLength/D");
                Double_t B0_PVDFit_decayLengthErr;                              t_data->Branch("B0_PVDFit_decayLengthErr", &B0_PVDFit_decayLengthErr, "B0_PVDFit_decayLengthErr/D");
                Double_t B0_PVDFit_nDOF;                                        t_data->Branch("B0_PVDFit_nDOF", &B0_PVDFit_nDOF, "B0_PVDFit_nDOF/D");
                Double_t B0_PVDFit_nIter;                                       t_data->Branch("B0_PVDFit_nIter", &B0_PVDFit_nIter, "B0_PVDFit_nIter/D");
                Double_t B0_PVDFit_status;                                      t_data->Branch("B0_PVDFit_status", &B0_PVDFit_status, "B0_PVDFit_status/D");
                Double_t B0_PVFit_Dplus_Kplus_ID;                               t_data->Branch("B0_PVFit_Dplus_Kplus_ID", &B0_PVFit_Dplus_Kplus_ID, "B0_PVFit_Dplus_Kplus_ID/D");
                Double_t B0_PVFit_Dplus_Kplus_PE;                               t_data->Branch("B0_PVFit_Dplus_Kplus_PE", &B0_PVFit_Dplus_Kplus_PE, "B0_PVFit_Dplus_Kplus_PE/D");
                Double_t B0_PVFit_Dplus_Kplus_PX;                               t_data->Branch("B0_PVFit_Dplus_Kplus_PX", &B0_PVFit_Dplus_Kplus_PX, "B0_PVFit_Dplus_Kplus_PX/D");
                Double_t B0_PVFit_Dplus_Kplus_PY;                               t_data->Branch("B0_PVFit_Dplus_Kplus_PY", &B0_PVFit_Dplus_Kplus_PY, "B0_PVFit_Dplus_Kplus_PY/D");
                Double_t B0_PVFit_Dplus_Kplus_PZ;                               t_data->Branch("B0_PVFit_Dplus_Kplus_PZ", &B0_PVFit_Dplus_Kplus_PZ, "B0_PVFit_Dplus_Kplus_PZ/D");
                Double_t B0_PVFit_Dplus_M;                                      t_data->Branch("B0_PVFit_Dplus_M", &B0_PVFit_Dplus_M, "B0_PVFit_Dplus_M/D");
                Double_t B0_PVFit_Dplus_MERR;                                   t_data->Branch("B0_PVFit_Dplus_MERR", &B0_PVFit_Dplus_MERR, "B0_PVFit_Dplus_MERR/D");
                Double_t B0_PVFit_Dplus_P;                                      t_data->Branch("B0_PVFit_Dplus_P", &B0_PVFit_Dplus_P, "B0_PVFit_Dplus_P/D");
                Double_t B0_PVFit_Dplus_PERR;                                   t_data->Branch("B0_PVFit_Dplus_PERR", &B0_PVFit_Dplus_PERR, "B0_PVFit_Dplus_PERR/D");
                Double_t B0_PVFit_Dplus_ctau;                                   t_data->Branch("B0_PVFit_Dplus_ctau", &B0_PVFit_Dplus_ctau, "B0_PVFit_Dplus_ctau/D");
                Double_t B0_PVFit_Dplus_ctauErr;                                t_data->Branch("B0_PVFit_Dplus_ctauErr", &B0_PVFit_Dplus_ctauErr, "B0_PVFit_Dplus_ctauErr/D");
                Double_t B0_PVFit_Dplus_decayLength;                            t_data->Branch("B0_PVFit_Dplus_decayLength", &B0_PVFit_Dplus_decayLength, "B0_PVFit_Dplus_decayLength/D");
                Double_t B0_PVFit_Dplus_decayLengthErr;                         t_data->Branch("B0_PVFit_Dplus_decayLengthErr", &B0_PVFit_Dplus_decayLengthErr, "B0_PVFit_Dplus_decayLengthErr/D");
                Double_t B0_PVFit_Dplus_piplus_0_ID;                            t_data->Branch("B0_PVFit_Dplus_piplus_0_ID", &B0_PVFit_Dplus_piplus_0_ID, "B0_PVFit_Dplus_piplus_0_ID/D");
                Double_t B0_PVFit_Dplus_piplus_0_PE;                            t_data->Branch("B0_PVFit_Dplus_piplus_0_PE", &B0_PVFit_Dplus_piplus_0_PE, "B0_PVFit_Dplus_piplus_0_PE/D");
                Double_t B0_PVFit_Dplus_piplus_0_PX;                            t_data->Branch("B0_PVFit_Dplus_piplus_0_PX", &B0_PVFit_Dplus_piplus_0_PX, "B0_PVFit_Dplus_piplus_0_PX/D");
                Double_t B0_PVFit_Dplus_piplus_0_PY;                            t_data->Branch("B0_PVFit_Dplus_piplus_0_PY", &B0_PVFit_Dplus_piplus_0_PY, "B0_PVFit_Dplus_piplus_0_PY/D");
                Double_t B0_PVFit_Dplus_piplus_0_PZ;                            t_data->Branch("B0_PVFit_Dplus_piplus_0_PZ", &B0_PVFit_Dplus_piplus_0_PZ, "B0_PVFit_Dplus_piplus_0_PZ/D");
                Double_t B0_PVFit_Dplus_piplus_ID;                              t_data->Branch("B0_PVFit_Dplus_piplus_ID", &B0_PVFit_Dplus_piplus_ID, "B0_PVFit_Dplus_piplus_ID/D");
                Double_t B0_PVFit_Dplus_piplus_PE;                              t_data->Branch("B0_PVFit_Dplus_piplus_PE", &B0_PVFit_Dplus_piplus_PE, "B0_PVFit_Dplus_piplus_PE/D");
                Double_t B0_PVFit_Dplus_piplus_PX;                              t_data->Branch("B0_PVFit_Dplus_piplus_PX", &B0_PVFit_Dplus_piplus_PX, "B0_PVFit_Dplus_piplus_PX/D");
                Double_t B0_PVFit_Dplus_piplus_PY;                              t_data->Branch("B0_PVFit_Dplus_piplus_PY", &B0_PVFit_Dplus_piplus_PY, "B0_PVFit_Dplus_piplus_PY/D");
                Double_t B0_PVFit_Dplus_piplus_PZ;                              t_data->Branch("B0_PVFit_Dplus_piplus_PZ", &B0_PVFit_Dplus_piplus_PZ, "B0_PVFit_Dplus_piplus_PZ/D");
                Double_t B0_PVFit_M;                                            t_data->Branch("B0_PVFit_M", &B0_PVFit_M, "B0_PVFit_M/D");
                Double_t B0_PVFit_MERR;                                         t_data->Branch("B0_PVFit_MERR", &B0_PVFit_MERR, "B0_PVFit_MERR/D");
                Double_t B0_PVFit_P;                                            t_data->Branch("B0_PVFit_P", &B0_PVFit_P, "B0_PVFit_P/D");
                Double_t B0_PVFit_PERR;                                         t_data->Branch("B0_PVFit_PERR", &B0_PVFit_PERR, "B0_PVFit_PERR/D");
                Double_t B0_PVFit_PV_X;                                         t_data->Branch("B0_PVFit_PV_X", &B0_PVFit_PV_X, "B0_PVFit_PV_X/D");
                Double_t B0_PVFit_PV_Y;                                         t_data->Branch("B0_PVFit_PV_Y", &B0_PVFit_PV_Y, "B0_PVFit_PV_Y/D");
                Double_t B0_PVFit_PV_Z;                                         t_data->Branch("B0_PVFit_PV_Z", &B0_PVFit_PV_Z, "B0_PVFit_PV_Z/D");
                Double_t B0_PVFit_PV_key;                                       t_data->Branch("B0_PVFit_PV_key", &B0_PVFit_PV_key, "B0_PVFit_PV_key/D");
                Double_t B0_PVFit_a_1_1260_plus_M;                              t_data->Branch("B0_PVFit_a_1_1260_plus_M", &B0_PVFit_a_1_1260_plus_M, "B0_PVFit_a_1_1260_plus_M/D");
                Double_t B0_PVFit_a_1_1260_plus_MERR;                           t_data->Branch("B0_PVFit_a_1_1260_plus_MERR", &B0_PVFit_a_1_1260_plus_MERR, "B0_PVFit_a_1_1260_plus_MERR/D");
                Double_t B0_PVFit_a_1_1260_plus_P;                              t_data->Branch("B0_PVFit_a_1_1260_plus_P", &B0_PVFit_a_1_1260_plus_P, "B0_PVFit_a_1_1260_plus_P/D");
                Double_t B0_PVFit_a_1_1260_plus_PERR;                           t_data->Branch("B0_PVFit_a_1_1260_plus_PERR", &B0_PVFit_a_1_1260_plus_PERR, "B0_PVFit_a_1_1260_plus_PERR/D");
                Double_t B0_PVFit_a_1_1260_plus_ctau;                           t_data->Branch("B0_PVFit_a_1_1260_plus_ctau", &B0_PVFit_a_1_1260_plus_ctau, "B0_PVFit_a_1_1260_plus_ctau/D");
                Double_t B0_PVFit_a_1_1260_plus_ctauErr;                        t_data->Branch("B0_PVFit_a_1_1260_plus_ctauErr", &B0_PVFit_a_1_1260_plus_ctauErr, "B0_PVFit_a_1_1260_plus_ctauErr/D");
                Double_t B0_PVFit_a_1_1260_plus_decayLength;                    t_data->Branch("B0_PVFit_a_1_1260_plus_decayLength", &B0_PVFit_a_1_1260_plus_decayLength, "B0_PVFit_a_1_1260_plus_decayLength/D");
                Double_t B0_PVFit_a_1_1260_plus_decayLengthErr;                 t_data->Branch("B0_PVFit_a_1_1260_plus_decayLengthErr", &B0_PVFit_a_1_1260_plus_decayLengthErr, "B0_PVFit_a_1_1260_plus_decayLengthErr/D");
                Double_t B0_PVFit_a_1_1260_plus_piplus_ID;                      t_data->Branch("B0_PVFit_a_1_1260_plus_piplus_ID", &B0_PVFit_a_1_1260_plus_piplus_ID, "B0_PVFit_a_1_1260_plus_piplus_ID/D");
                Double_t B0_PVFit_a_1_1260_plus_piplus_PE;                      t_data->Branch("B0_PVFit_a_1_1260_plus_piplus_PE", &B0_PVFit_a_1_1260_plus_piplus_PE, "B0_PVFit_a_1_1260_plus_piplus_PE/D");
                Double_t B0_PVFit_a_1_1260_plus_piplus_PX;                      t_data->Branch("B0_PVFit_a_1_1260_plus_piplus_PX", &B0_PVFit_a_1_1260_plus_piplus_PX, "B0_PVFit_a_1_1260_plus_piplus_PX/D");
                Double_t B0_PVFit_a_1_1260_plus_piplus_PY;                      t_data->Branch("B0_PVFit_a_1_1260_plus_piplus_PY", &B0_PVFit_a_1_1260_plus_piplus_PY, "B0_PVFit_a_1_1260_plus_piplus_PY/D");
                Double_t B0_PVFit_a_1_1260_plus_piplus_PZ;                      t_data->Branch("B0_PVFit_a_1_1260_plus_piplus_PZ", &B0_PVFit_a_1_1260_plus_piplus_PZ, "B0_PVFit_a_1_1260_plus_piplus_PZ/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_0_ID;                     t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_0_ID", &B0_PVFit_a_1_1260_plus_pplus_0_ID, "B0_PVFit_a_1_1260_plus_pplus_0_ID/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_0_PE;                     t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_0_PE", &B0_PVFit_a_1_1260_plus_pplus_0_PE, "B0_PVFit_a_1_1260_plus_pplus_0_PE/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_0_PX;                     t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_0_PX", &B0_PVFit_a_1_1260_plus_pplus_0_PX, "B0_PVFit_a_1_1260_plus_pplus_0_PX/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_0_PY;                     t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_0_PY", &B0_PVFit_a_1_1260_plus_pplus_0_PY, "B0_PVFit_a_1_1260_plus_pplus_0_PY/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_0_PZ;                     t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_0_PZ", &B0_PVFit_a_1_1260_plus_pplus_0_PZ, "B0_PVFit_a_1_1260_plus_pplus_0_PZ/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_ID;                       t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_ID", &B0_PVFit_a_1_1260_plus_pplus_ID, "B0_PVFit_a_1_1260_plus_pplus_ID/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_PE;                       t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_PE", &B0_PVFit_a_1_1260_plus_pplus_PE, "B0_PVFit_a_1_1260_plus_pplus_PE/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_PX;                       t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_PX", &B0_PVFit_a_1_1260_plus_pplus_PX, "B0_PVFit_a_1_1260_plus_pplus_PX/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_PY;                       t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_PY", &B0_PVFit_a_1_1260_plus_pplus_PY, "B0_PVFit_a_1_1260_plus_pplus_PY/D");
                Double_t B0_PVFit_a_1_1260_plus_pplus_PZ;                       t_data->Branch("B0_PVFit_a_1_1260_plus_pplus_PZ", &B0_PVFit_a_1_1260_plus_pplus_PZ, "B0_PVFit_a_1_1260_plus_pplus_PZ/D");
                Double_t B0_PVFit_chi2;                                         t_data->Branch("B0_PVFit_chi2", &B0_PVFit_chi2, "B0_PVFit_chi2/D");
                Double_t B0_PVFit_ctau;                                         t_data->Branch("B0_PVFit_ctau", &B0_PVFit_ctau, "B0_PVFit_ctau/D");
                Double_t B0_PVFit_ctauErr;                                      t_data->Branch("B0_PVFit_ctauErr", &B0_PVFit_ctauErr, "B0_PVFit_ctauErr/D");
                Double_t B0_PVFit_decayLength;                                  t_data->Branch("B0_PVFit_decayLength", &B0_PVFit_decayLength, "B0_PVFit_decayLength/D");
                Double_t B0_PVFit_decayLengthErr;                               t_data->Branch("B0_PVFit_decayLengthErr", &B0_PVFit_decayLengthErr, "B0_PVFit_decayLengthErr/D");
                Double_t B0_PVFit_nDOF;                                         t_data->Branch("B0_PVFit_nDOF", &B0_PVFit_nDOF, "B0_PVFit_nDOF/D");
                Double_t B0_PVFit_nIter;                                        t_data->Branch("B0_PVFit_nIter", &B0_PVFit_nIter, "B0_PVFit_nIter/D");
                Double_t B0_PVFit_status;                                       t_data->Branch("B0_PVFit_status", &B0_PVFit_status, "B0_PVFit_status/D");
                
                Int_t N = dis_chain->GetEntries();

                cout<< "total entries :"<<N<<endl;
                make_clean_mc_B2Dpppi tag(dis_chain);
                for(Int_t ii=0; ii<N; ii++){
                                if(ii==Int_t(N*0.1)) cout<<"**********completed  10%"<<"*********"<<endl;
                                if(ii==Int_t(N*0.2)) cout<<"**********completed  20%"<<"*********"<<endl;
                                if(ii==Int_t(N*0.3)) cout<<"**********completed  30%"<<"*********"<<endl;
                                if(ii==Int_t(N*0.4)) cout<<"**********completed  40%"<<"*********"<<endl;
                                if(ii==Int_t(N*0.5)) cout<<"**********completed  50%"<<"*********"<<endl;
                                if(ii==Int_t(N*0.6)) cout<<"**********completed  60%"<<"*********"<<endl;
                                if(ii==Int_t(N*0.7)) cout<<"**********completed  70%"<<"*********"<<endl;
                                if(ii==Int_t(N*0.8)) cout<<"**********completed  80%"<<"*********"<<endl;
                                if(ii==Int_t(N*0.9)) cout<<"**********completed  90%"<<"*********"<<endl;
                                if(ii==Int_t(N*1-1)) cout<<"**********completed 100%"<<"*********"<<endl;

                                tag.GetEntry(ii);
				B0_PVALLFit_Dplus_Kplus_ID = tag.B0_PVALLFit_Dplus_Kplus_ID[0];
				B0_PVALLFit_Dplus_Kplus_PE = tag.B0_PVALLFit_Dplus_Kplus_PE[0];
				B0_PVALLFit_Dplus_Kplus_PX = tag.B0_PVALLFit_Dplus_Kplus_PX[0];
				B0_PVALLFit_Dplus_Kplus_PY = tag.B0_PVALLFit_Dplus_Kplus_PY[0];
				B0_PVALLFit_Dplus_Kplus_PZ = tag.B0_PVALLFit_Dplus_Kplus_PZ[0];
				B0_PVALLFit_Dplus_M = tag.B0_PVALLFit_Dplus_M[0];
                                B0_PVALLFit_Dplus_MERR = tag.B0_PVALLFit_Dplus_MERR[0];
				B0_PVALLFit_Dplus_P = tag.B0_PVALLFit_Dplus_P[0];
				B0_PVALLFit_Dplus_PERR = tag.B0_PVALLFit_Dplus_PERR[0];
                                B0_PVALLFit_Dplus_ctau = tag.B0_PVALLFit_Dplus_ctau[0];
                                B0_PVALLFit_Dplus_ctauErr = tag.B0_PVALLFit_Dplus_ctauErr[0];
                                B0_PVALLFit_Dplus_decayLength = tag.B0_PVALLFit_Dplus_decayLength[0];
                                B0_PVALLFit_Dplus_decayLengthErr = tag.B0_PVALLFit_Dplus_decayLengthErr[0];
                                B0_PVALLFit_Dplus_piplus_0_ID = tag.B0_PVALLFit_Dplus_piplus_0_ID[0];
                                B0_PVALLFit_Dplus_piplus_0_PE = tag.B0_PVALLFit_Dplus_piplus_0_PE[0];
                                B0_PVALLFit_Dplus_piplus_0_PX = tag.B0_PVALLFit_Dplus_piplus_0_PX[0];
                                B0_PVALLFit_Dplus_piplus_0_PY = tag.B0_PVALLFit_Dplus_piplus_0_PY[0];
                                B0_PVALLFit_Dplus_piplus_0_PZ = tag.B0_PVALLFit_Dplus_piplus_0_PZ[0];
                                B0_PVALLFit_Dplus_piplus_ID = tag.B0_PVALLFit_Dplus_piplus_ID[0];
                                B0_PVALLFit_Dplus_piplus_PE = tag.B0_PVALLFit_Dplus_piplus_PE[0];
                                B0_PVALLFit_Dplus_piplus_PX = tag.B0_PVALLFit_Dplus_piplus_PX[0];
                                B0_PVALLFit_Dplus_piplus_PY = tag.B0_PVALLFit_Dplus_piplus_PY[0];
                                B0_PVALLFit_Dplus_piplus_PZ = tag.B0_PVALLFit_Dplus_piplus_PZ[0];
                                B0_PVALLFit_M = tag.B0_PVALLFit_M[0];
                                B0_PVALLFit_MERR = tag.B0_PVALLFit_MERR[0];
                                B0_PVALLFit_P = tag.B0_PVALLFit_P[0];
                                B0_PVALLFit_PERR = tag.B0_PVALLFit_PERR[0];
                                B0_PVALLFit_PV_X = tag.B0_PVALLFit_PV_X[0];
                                B0_PVALLFit_PV_Y = tag.B0_PVALLFit_PV_Y[0];
                                B0_PVALLFit_PV_Z = tag.B0_PVALLFit_PV_Z[0];
                                B0_PVALLFit_PV_key = tag.B0_PVALLFit_PV_key[0];
                                B0_PVALLFit_a_1_1260_plus_M = tag.B0_PVALLFit_a_1_1260_plus_M[0];
                                B0_PVALLFit_a_1_1260_plus_MERR = tag.B0_PVALLFit_a_1_1260_plus_MERR[0];
                                B0_PVALLFit_a_1_1260_plus_P = tag.B0_PVALLFit_a_1_1260_plus_P[0];
                                B0_PVALLFit_a_1_1260_plus_PERR = tag.B0_PVALLFit_a_1_1260_plus_PERR[0];
                                B0_PVALLFit_a_1_1260_plus_ctau = tag.B0_PVALLFit_a_1_1260_plus_ctau[0];
                                B0_PVALLFit_a_1_1260_plus_ctauErr = tag.B0_PVALLFit_a_1_1260_plus_ctauErr[0];
                                B0_PVALLFit_a_1_1260_plus_decayLength = tag.B0_PVALLFit_a_1_1260_plus_decayLength[0];
                                B0_PVALLFit_a_1_1260_plus_decayLengthErr = tag.B0_PVALLFit_a_1_1260_plus_decayLengthErr[0];
                                B0_PVALLFit_a_1_1260_plus_piplus_ID = tag.B0_PVALLFit_a_1_1260_plus_piplus_ID[0];
                                B0_PVALLFit_a_1_1260_plus_piplus_PE = tag.B0_PVALLFit_a_1_1260_plus_piplus_PE[0];
                                B0_PVALLFit_a_1_1260_plus_piplus_PX = tag.B0_PVALLFit_a_1_1260_plus_piplus_PX[0];
                                B0_PVALLFit_a_1_1260_plus_piplus_PY = tag.B0_PVALLFit_a_1_1260_plus_piplus_PY[0];
                                B0_PVALLFit_a_1_1260_plus_piplus_PZ = tag.B0_PVALLFit_a_1_1260_plus_piplus_PZ[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_0_ID = tag.B0_PVALLFit_a_1_1260_plus_pplus_0_ID[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_0_PE = tag.B0_PVALLFit_a_1_1260_plus_pplus_0_PE[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_0_PX = tag.B0_PVALLFit_a_1_1260_plus_pplus_0_PX[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_0_PY = tag.B0_PVALLFit_a_1_1260_plus_pplus_0_PY[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_0_PZ = tag.B0_PVALLFit_a_1_1260_plus_pplus_0_PZ[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_ID = tag.B0_PVALLFit_a_1_1260_plus_pplus_ID[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_PE = tag.B0_PVALLFit_a_1_1260_plus_pplus_PE[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_PX = tag.B0_PVALLFit_a_1_1260_plus_pplus_PX[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_PY = tag.B0_PVALLFit_a_1_1260_plus_pplus_PY[0];
                                B0_PVALLFit_a_1_1260_plus_pplus_PZ = tag.B0_PVALLFit_a_1_1260_plus_pplus_PZ[0];
                                B0_PVALLFit_chi2 = tag.B0_PVALLFit_chi2[0];
                                B0_PVALLFit_ctau = tag.B0_PVALLFit_ctau[0];
                                B0_PVALLFit_ctauErr = tag.B0_PVALLFit_ctauErr[0];
                                B0_PVALLFit_decayLength = tag.B0_PVALLFit_decayLength[0];
                                B0_PVALLFit_decayLengthErr = tag.B0_PVALLFit_decayLengthErr[0];
                                B0_PVALLFit_nDOF = tag.B0_PVALLFit_nDOF[0];
                                B0_PVALLFit_nIter = tag.B0_PVALLFit_nIter[0];
                                B0_PVALLFit_status = tag.B0_PVALLFit_status[0];
                                B0_PVDFit_Dplus_Kplus_ID = tag.B0_PVDFit_Dplus_Kplus_ID[0];
                                B0_PVDFit_Dplus_Kplus_PE = tag.B0_PVDFit_Dplus_Kplus_PE[0];
                                B0_PVDFit_Dplus_Kplus_PX = tag.B0_PVDFit_Dplus_Kplus_PX[0];
                                B0_PVDFit_Dplus_Kplus_PY = tag.B0_PVDFit_Dplus_Kplus_PY[0];
                                B0_PVDFit_Dplus_Kplus_PZ = tag.B0_PVDFit_Dplus_Kplus_PZ[0];
                                B0_PVDFit_Dplus_M = tag.B0_PVDFit_Dplus_M[0];
                                B0_PVDFit_Dplus_MERR = tag.B0_PVDFit_Dplus_MERR[0];
                                B0_PVDFit_Dplus_P = tag.B0_PVDFit_Dplus_P[0];
                                B0_PVDFit_Dplus_PERR = tag.B0_PVDFit_Dplus_PERR[0];
                                B0_PVDFit_Dplus_ctau = tag.B0_PVDFit_Dplus_ctau[0];
                                B0_PVDFit_Dplus_ctauErr = tag.B0_PVDFit_Dplus_ctauErr[0];
                                B0_PVDFit_Dplus_decayLength = tag.B0_PVDFit_Dplus_decayLength[0];
                                B0_PVDFit_Dplus_decayLengthErr = tag.B0_PVDFit_Dplus_decayLengthErr[0];
                                B0_PVDFit_Dplus_piplus_0_ID = tag.B0_PVDFit_Dplus_piplus_0_ID[0];
                                B0_PVDFit_Dplus_piplus_0_PE = tag.B0_PVDFit_Dplus_piplus_0_PE[0];
                                B0_PVDFit_Dplus_piplus_0_PX = tag.B0_PVDFit_Dplus_piplus_0_PX[0];
                                B0_PVDFit_Dplus_piplus_0_PY = tag.B0_PVDFit_Dplus_piplus_0_PY[0];
                                B0_PVDFit_Dplus_piplus_0_PZ = tag.B0_PVDFit_Dplus_piplus_0_PZ[0];
                                B0_PVDFit_Dplus_piplus_ID = tag.B0_PVDFit_Dplus_piplus_ID[0];
                                B0_PVDFit_Dplus_piplus_PE = tag.B0_PVDFit_Dplus_piplus_PE[0];
                                B0_PVDFit_Dplus_piplus_PX = tag.B0_PVDFit_Dplus_piplus_PX[0];
                                B0_PVDFit_Dplus_piplus_PY = tag.B0_PVDFit_Dplus_piplus_PY[0];
                                B0_PVDFit_Dplus_piplus_PZ = tag.B0_PVDFit_Dplus_piplus_PZ[0];
                                B0_PVDFit_M = tag.B0_PVDFit_M[0];
                                B0_PVDFit_MERR = tag.B0_PVDFit_MERR[0];
                                B0_PVDFit_P = tag.B0_PVDFit_P[0];
                                B0_PVDFit_PERR = tag.B0_PVDFit_PERR[0];
                                B0_PVDFit_PV_X = tag.B0_PVDFit_PV_X[0];
                                B0_PVDFit_PV_Y = tag.B0_PVDFit_PV_Y[0];
                                B0_PVDFit_PV_Z = tag.B0_PVDFit_PV_Z[0];
                                B0_PVDFit_PV_key = tag.B0_PVDFit_PV_key[0];
                                B0_PVDFit_a_1_1260_plus_M = tag.B0_PVDFit_a_1_1260_plus_M[0];
                                B0_PVDFit_a_1_1260_plus_MERR = tag.B0_PVDFit_a_1_1260_plus_MERR[0];
                                B0_PVDFit_a_1_1260_plus_P = tag.B0_PVDFit_a_1_1260_plus_P[0];
                                B0_PVDFit_a_1_1260_plus_PERR = tag.B0_PVDFit_a_1_1260_plus_PERR[0];
                                B0_PVDFit_a_1_1260_plus_ctau = tag.B0_PVDFit_a_1_1260_plus_ctau[0];
                                B0_PVDFit_a_1_1260_plus_ctauErr = tag.B0_PVDFit_a_1_1260_plus_ctauErr[0];
                                B0_PVDFit_a_1_1260_plus_decayLength = tag.B0_PVDFit_a_1_1260_plus_decayLength[0];
                                B0_PVDFit_a_1_1260_plus_decayLengthErr = tag.B0_PVDFit_a_1_1260_plus_decayLengthErr[0];
                                B0_PVDFit_a_1_1260_plus_piplus_ID = tag.B0_PVDFit_a_1_1260_plus_piplus_ID[0];
                                B0_PVDFit_a_1_1260_plus_piplus_PE = tag.B0_PVDFit_a_1_1260_plus_piplus_PE[0];
                                B0_PVDFit_a_1_1260_plus_piplus_PX = tag.B0_PVDFit_a_1_1260_plus_piplus_PX[0];
                                B0_PVDFit_a_1_1260_plus_piplus_PY = tag.B0_PVDFit_a_1_1260_plus_piplus_PY[0];
                                B0_PVDFit_a_1_1260_plus_piplus_PZ = tag.B0_PVDFit_a_1_1260_plus_piplus_PZ[0];
                                B0_PVDFit_a_1_1260_plus_pplus_0_ID = tag.B0_PVDFit_a_1_1260_plus_pplus_0_ID[0];
                                B0_PVDFit_a_1_1260_plus_pplus_0_PE = tag.B0_PVDFit_a_1_1260_plus_pplus_0_PE[0];
                                B0_PVDFit_a_1_1260_plus_pplus_0_PX = tag.B0_PVDFit_a_1_1260_plus_pplus_0_PX[0];
                                B0_PVDFit_a_1_1260_plus_pplus_0_PY = tag.B0_PVDFit_a_1_1260_plus_pplus_0_PY[0];
                                B0_PVDFit_a_1_1260_plus_pplus_0_PZ = tag.B0_PVDFit_a_1_1260_plus_pplus_0_PZ[0];
                                B0_PVDFit_a_1_1260_plus_pplus_ID = tag.B0_PVDFit_a_1_1260_plus_pplus_ID[0];
                                B0_PVDFit_a_1_1260_plus_pplus_PE = tag.B0_PVDFit_a_1_1260_plus_pplus_PE[0];
                                B0_PVDFit_a_1_1260_plus_pplus_PX = tag.B0_PVDFit_a_1_1260_plus_pplus_PX[0];
                                B0_PVDFit_a_1_1260_plus_pplus_PY = tag.B0_PVDFit_a_1_1260_plus_pplus_PY[0];
                                B0_PVDFit_a_1_1260_plus_pplus_PZ = tag.B0_PVDFit_a_1_1260_plus_pplus_PZ[0];
                                B0_PVDFit_chi2 = tag.B0_PVDFit_chi2[0];
                                B0_PVDFit_ctau = tag.B0_PVDFit_ctau[0];
                                B0_PVDFit_ctauErr = tag.B0_PVDFit_ctauErr[0];
                                B0_PVDFit_decayLength = tag.B0_PVDFit_decayLength[0];
                                B0_PVDFit_decayLengthErr = tag.B0_PVDFit_decayLengthErr[0];
                                B0_PVDFit_nDOF = tag.B0_PVDFit_nDOF[0];
                                B0_PVDFit_nIter = tag.B0_PVDFit_nIter[0];
                                B0_PVDFit_status = tag.B0_PVDFit_status[0];
                                B0_PVFit_Dplus_Kplus_ID = tag.B0_PVFit_Dplus_Kplus_ID[0];
                                B0_PVFit_Dplus_Kplus_PE = tag.B0_PVFit_Dplus_Kplus_PE[0];
                                B0_PVFit_Dplus_Kplus_PX = tag.B0_PVFit_Dplus_Kplus_PX[0];
                                B0_PVFit_Dplus_Kplus_PY = tag.B0_PVFit_Dplus_Kplus_PY[0];
                                B0_PVFit_Dplus_Kplus_PZ = tag.B0_PVFit_Dplus_Kplus_PZ[0];
                                B0_PVFit_Dplus_M = tag.B0_PVFit_Dplus_M[0];
                                B0_PVFit_Dplus_MERR = tag.B0_PVFit_Dplus_MERR[0];
                                B0_PVFit_Dplus_P = tag.B0_PVFit_Dplus_P[0];
                                B0_PVFit_Dplus_PERR = tag.B0_PVFit_Dplus_PERR[0];
                                B0_PVFit_Dplus_ctau = tag.B0_PVFit_Dplus_ctau[0];
                                B0_PVFit_Dplus_ctauErr = tag.B0_PVFit_Dplus_ctauErr[0];
                                B0_PVFit_Dplus_decayLength = tag.B0_PVFit_Dplus_decayLength[0];
                                B0_PVFit_Dplus_decayLengthErr = tag.B0_PVFit_Dplus_decayLengthErr[0];
                                B0_PVFit_Dplus_piplus_0_ID = tag.B0_PVFit_Dplus_piplus_0_ID[0];
                                B0_PVFit_Dplus_piplus_0_PE = tag.B0_PVFit_Dplus_piplus_0_PE[0];
                                B0_PVFit_Dplus_piplus_0_PX = tag.B0_PVFit_Dplus_piplus_0_PX[0];
                                B0_PVFit_Dplus_piplus_0_PY = tag.B0_PVFit_Dplus_piplus_0_PY[0];
                                B0_PVFit_Dplus_piplus_0_PZ = tag.B0_PVFit_Dplus_piplus_0_PZ[0];
                                B0_PVFit_Dplus_piplus_ID = tag.B0_PVFit_Dplus_piplus_ID[0];
                                B0_PVFit_Dplus_piplus_PE = tag.B0_PVFit_Dplus_piplus_PE[0];
                                B0_PVFit_Dplus_piplus_PX = tag.B0_PVFit_Dplus_piplus_PX[0];
                                B0_PVFit_Dplus_piplus_PY = tag.B0_PVFit_Dplus_piplus_PY[0];
                                B0_PVFit_Dplus_piplus_PZ = tag.B0_PVFit_Dplus_piplus_PZ[0];
                                B0_PVFit_M = tag.B0_PVFit_M[0];
                                B0_PVFit_MERR = tag.B0_PVFit_MERR[0];
                                B0_PVFit_P = tag.B0_PVFit_P[0];
                                B0_PVFit_PERR = tag.B0_PVFit_PERR[0];
                                B0_PVFit_PV_X = tag.B0_PVFit_PV_X[0];
                                B0_PVFit_PV_Y = tag.B0_PVFit_PV_Y[0];
                                B0_PVFit_PV_Z = tag.B0_PVFit_PV_Z[0];
                                B0_PVFit_PV_key = tag.B0_PVFit_PV_key[0];
                                B0_PVFit_a_1_1260_plus_M = tag.B0_PVFit_a_1_1260_plus_M[0];
                                B0_PVFit_a_1_1260_plus_MERR = tag.B0_PVFit_a_1_1260_plus_MERR[0];
                                B0_PVFit_a_1_1260_plus_P = tag.B0_PVFit_a_1_1260_plus_P[0];
                                B0_PVFit_a_1_1260_plus_PERR = tag.B0_PVFit_a_1_1260_plus_PERR[0];
                                B0_PVFit_a_1_1260_plus_ctau = tag.B0_PVFit_a_1_1260_plus_ctau[0];
                                B0_PVFit_a_1_1260_plus_ctauErr = tag.B0_PVFit_a_1_1260_plus_ctauErr[0];
                                B0_PVFit_a_1_1260_plus_decayLength = tag.B0_PVFit_a_1_1260_plus_decayLength[0];
                                B0_PVFit_a_1_1260_plus_decayLengthErr = tag.B0_PVFit_a_1_1260_plus_decayLengthErr[0];
                                B0_PVFit_a_1_1260_plus_piplus_ID = tag.B0_PVFit_a_1_1260_plus_piplus_ID[0];
                                B0_PVFit_a_1_1260_plus_piplus_PE = tag.B0_PVFit_a_1_1260_plus_piplus_PE[0];
                                B0_PVFit_a_1_1260_plus_piplus_PX = tag.B0_PVFit_a_1_1260_plus_piplus_PX[0];
                                B0_PVFit_a_1_1260_plus_piplus_PY = tag.B0_PVFit_a_1_1260_plus_piplus_PY[0];
                                B0_PVFit_a_1_1260_plus_piplus_PZ = tag.B0_PVFit_a_1_1260_plus_piplus_PZ[0];
                                B0_PVFit_a_1_1260_plus_pplus_0_ID = tag.B0_PVFit_a_1_1260_plus_pplus_0_ID[0];
                                B0_PVFit_a_1_1260_plus_pplus_0_PE = tag.B0_PVFit_a_1_1260_plus_pplus_0_PE[0];
                                B0_PVFit_a_1_1260_plus_pplus_0_PX = tag.B0_PVFit_a_1_1260_plus_pplus_0_PX[0];
                                B0_PVFit_a_1_1260_plus_pplus_0_PY = tag.B0_PVFit_a_1_1260_plus_pplus_0_PY[0];
                                B0_PVFit_a_1_1260_plus_pplus_0_PZ = tag.B0_PVFit_a_1_1260_plus_pplus_0_PZ[0];
                                B0_PVFit_a_1_1260_plus_pplus_ID = tag.B0_PVFit_a_1_1260_plus_pplus_ID[0];
                                B0_PVFit_a_1_1260_plus_pplus_PE = tag.B0_PVFit_a_1_1260_plus_pplus_PE[0];
                                B0_PVFit_a_1_1260_plus_pplus_PX = tag.B0_PVFit_a_1_1260_plus_pplus_PX[0];
                                B0_PVFit_a_1_1260_plus_pplus_PY = tag.B0_PVFit_a_1_1260_plus_pplus_PY[0];
                                B0_PVFit_a_1_1260_plus_pplus_PZ = tag.B0_PVFit_a_1_1260_plus_pplus_PZ[0];
                                B0_PVFit_chi2 = tag.B0_PVFit_chi2[0];
                                B0_PVFit_ctau = tag.B0_PVFit_ctau[0];
                                B0_PVFit_ctauErr = tag.B0_PVFit_ctauErr[0];
                                B0_PVFit_decayLength = tag.B0_PVFit_decayLength[0];
                                B0_PVFit_decayLengthErr = tag.B0_PVFit_decayLengthErr[0];
                                B0_PVFit_nDOF = tag.B0_PVFit_nDOF[0];
                                B0_PVFit_nIter = tag.B0_PVFit_nIter[0];
                                B0_PVFit_status = tag.B0_PVFit_status[0];
                                t_data->Fill();
		}

		newf->cd();
		t_data->Write();

}
